### ISSUE TITLE
[feature] Implement all remaining XPath and XQuery 3.1 Functions & Operators

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#3635]
According to https://github.com/eXist-db/documentation/blob/master/src/main/xar-resources/data/xquery/xquery.xml#L111-L149, the current list of functions not implemented in eXist is:

- [ ] `fn:collation-key#1, #2`
- [ ] `fn:default-language#0`
- [ ] `fn:document-uri#0`
- [ ] `fn:element-with-id#1, #2`
- [ ] `fn:format-integer#2, #3`
- [ ] `fn:nilled#0`
- [ ] `fn:path#0, #1`
- [ ] `fn:round#2`
- [ ] `fn:transform#1`
- [ ] `fn:uri-collection#0, #1`
- [ ] `map:find#2`
- [ ] `map:merge#2`

**Comment by yamahito** [comment]
+1 for `uri-collection()`!

**Comment by joewiz** [comment]
All implemented in `develop`
