### ISSUE TITLE
[Master issue] Prepare 5.4.0 and/or 6.0.0 release

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#3968]
5.4.0 (already a feature release since we've updated libraries)
- [x] fix mail module https://github.com/eXist-db/exist/pull/3994
- [x] implement map:merge#2 for 5.4.0 https://github.com/eXist-db/exist/pull/4002

if possible align with the release:

- [x] Update exist-db.org with eXist 5.3.0 and updated core apps
- [ ] Fix Dashboard login issue

5.4.1 or 5.5.0
- [x] New eXide release with fixes:
    - [x] Repair opening document in eXide https://github.com/eXist-db/eXide/issues/322 
    - [x] New Application Menu was disabled https://github.com/eXist-db/eXide/issues/323
- [ ] Fix the issue for users, whereby when the update to a newer eXist-db version, the Dashboard etc, doesn't work and they are told they have to "Clear the Browser" cache to fix it. Could it be a cookie issue?
- [x] Signing and notarization - https://github.com/eXist-db/exist/issues/3961
- [x] Ensure updated Package Service is released for inclusion in the eXist-db release - https://github.com/eXist-db/existdb-packageservice/pull/22
- [ ] publish updated “howto release” document #3962 + #3952
- [ ] Github-release-plugin: fix link to release notes and improve layout
- [x] fix unary lookups #3966 
- [x] NPE in SimpleACLPermission  #4009 

6.0.0
- [ ] Maps\* - a follow-on PR just for 6.0.0 to https://github.com/eXist-db/exist/pull/3738
- [ ] Security - core+Saxon - add option to limit RFI in fn:doc etc\* - https://github.com/eXist-db/exist/issues/3927
- [x] Security - core\* - Apache XML-RPC CVE-2019-17570 / CVE-2016-5002 - https://github.com/eXist-db/exist/issues/3063 https://github.com/eXist-db/exist/pull/3934 (introduces a breaking change)
- [x] Security [CVE-2021-45046](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45046) Log4shell 2.0 https://github.com/eXist-db/exist/pull/4119 (reverted) 650e6d05440a0d9d23a19d525e55e9eaa6dde473

**Comment by line-o** [comment]
There is a PR that will only extend the testsuite with the tests for immutable maps #3725

**Comment by joewiz** [comment]
Two more are items from this list are now checked off:

1. "Update exist-db.org with eXist 5.3.0 and updated core apps" - thanks to @wolfgangmm posting 5.3.0 to exist-db.org
2. "Signing and notarization" - thanks to @adamretter backporting the solution and notarizing this week's newly released binaries

Is this list still useful? I'll add this topic to the agenda for Monday's Community Call.

**Comment by joewiz** [comment]
Closing this now, with these follow-on actions to be done:

- "Dashboard login issue" - reopened as https://github.com/eXist-db/dashboard/issues/129. JW will open and check if it is a duplicate of "Fix the issue for users, whereby when the update to a newer eXist-db version, the Dashboard etc, doesn't work and they are told they have to "Clear the Browser" cache to fix it. Could it be a cookie issue?" 
- Re "update howto release”, the release notes for 4.x and 5.x do work for @adamretter.  Action: the next non-Adam person to do a release will review the release documentation and confirm if it can work or not.
- Re: "Github-release-plugin: fix link to release notes and improve layout" - still needs to be done but needs an issue to track it. - @line-o will create an issue.
